<fieldset>
    <div class="clearfix">
        <label for="title">邮箱：</label>
        <div class="input">
            <?php echo $this->element->getElement('email')?>
        </div>
    </div>
    <div class="clearfix">
        <label for="content">密码：</label>
        <div class="input">
            <?php echo $this->element->getElement('password')?>
        </div>
    </div>
    <div class="actions">
        <?php echo $this->element->getElement('submit')?>
    </div>
</fieldset>
