<fieldset>
    <div class="clearfix">
        <label for="title">邮箱：</label>
        <div class="input">
            <input type="text" size="30" name="email" id="email" class="xlarge" />
        </div>
    </div>
    <div class="clearfix">
        <label for="content">密码：</label>
        <div class="input">
            <input type="password" size="30" name="password" id="password" class="xlarge" />
        </div>
    </div>
    <div class="actions">
        <input type="submit" value="登录" class="btn primary">
    </div>
</fieldset>
