<?php $message = $this->element->getMessages()?>
<fieldset>
    <div class="clearfix<?php if(isset($message['email'])):?> error<?php endif;?>">
        <label for="title">邮箱：</label>
        <div class="input">
            <?php echo $this->element->getElement('email')?>
            <?php if(isset($message['email'])):?>
            <span class="help-inline">
                <?php foreach($message['email'] as $info):?>
                <?php echo $info?>
                <?php endforeach;?>
            </span>
            <?php endif;?>
        </div>
    </div>
    <div class="clearfix<?php if(isset($message['password'])):?> error<?php endif;?>">
        <label for="content">密码：</label>
        <div class="input">
            <?php echo $this->element->getElement('password')?>
            <?php if(isset($message['password'])):?>
            <span class="help-inline">
                <?php foreach($message['password'] as $info):?>
                <?php echo $info?>
                <?php endforeach;?>
            </span>
            <?php endif;?>
        </div>
    </div>
    <div class="clearfix<?php if(isset($message['password2'])):?> error<?php endif;?>">
        <label for="content">重复密码：</label>
        <div class="input">
            <?php echo $this->element->getElement('password2')?>
            <?php if(isset($message['password2'])):?>
            <span class="help-inline">
                <?php foreach($message['password2'] as $info):?>
                <?php echo $info?>
                <?php endforeach;?>
            </span>
            <?php endif;?>
        </div>
    </div>
    <div class="clearfix<?php if(isset($message['nickname'])):?> error<?php endif;?>">
        <label for="content">名号：</label>
        <div class="input">
            <?php echo $this->element->getElement('nickname')?>
            <?php if(isset($message['nickname'])):?>
            <span class="help-inline">
                <?php foreach($message['nickname'] as $info):?>
                <?php echo $info?>
                <?php endforeach;?>
            </span>
            <?php endif;?>
        </div>
    </div>
    <div class="actions">
        <?php echo $this->element->getElement('submit')?>&nbsp;
        <button class="btn" type="reset">重填</button>
    </div>
</fieldset>
