<fieldset>
    <div class="clearfix">
        <label for="title">邮箱：</label>
        <div class="input">
            <?php echo $this->element->getElement('email')?>
        </div>
    </div>
    <div class="clearfix">
        <label for="content">密码：</label>
        <div class="input">
            <?php echo $this->element->getElement('password')?>   
        </div>
    </div>
    <div class="clearfix">
        <label for="content">重复密码：</label>
        <div class="input">
            <?php echo $this->element->getElement('password2')?>   
        </div>
    </div>
    <div class="clearfix">
        <label for="content">名号：</label>
        <div class="input">
            <?php echo $this->element->getElement('nickname')?>   
        </div>
    </div>
    <div class="actions">
        <?php echo $this->element->getElement('submit')?>&nbsp;
        <button class="btn" type="reset">重填</button>
    </div>
</fieldset>
