<div class="span11">
    <div id="index-recent-topic-list" class="row show-grid">
        <?php foreach($this->recentTopics as $topic):?>
        <div class="index-recent-topic span11">
            <h3>
                <a href="<?php echo $this->url(array(
                    'topicId' => $topic->getId(),
                ), 'topicView', true);?>"><?php echo $this->escape($topic->getTitle());?>，你们有什么想问的？</a>
            </h3>
            <p>
                <?php echo $this->escape($topic->getContent());?>
            </p>
        </div>
        <?php endforeach;?>
        <a id="index-small-ask-button" class="btn small primary" href="<?php echo $this->url(array(
            'controller' => 'topic',
            'action'       => 'new',
        ))?>">我是OOXX，向我提问吧！</a>
    </div>
</div>
<div class="span5">
    
    <a id="index-big-ask-button" class="btn large primary" href="<?php echo $this->url(array(
        'controller' => 'topic',
        'action'     => 'new'
    ))?>">
        我是OOXX，向我提问吧！
    </a>

    <div id="index-hot-topic-list" class="row show-grid">
        <?php foreach($this->hotTopics as $topic):?>
        <div class="index-hot-topic span5">
            <a href="<?php echo $this->url(array(
                    'topicId' => $topic->getId(),
                ), 'topicView', true);?>"><?php echo $this->escape($topic->getTitle());?>，你们有什么想问的？</a>
            <p>
                <?php echo $this->escape($topic->getContent());?>
            </p>
        </div>
        <?php endforeach;?>
    </div>
</div>
