<div id="topic-example">
    <h3>例子：</h3>
    <ul>
        <li>我是门口摊大饼的，你们有什么想问的？</li>
        <li>我是一个在非洲厮混过几年的颓废男纸，你们有什么想问的？</li>
        <li>我的男朋友是外国人，你们有什么想问的？</li>
        <li>我是单身女青年，有什么想问的？</li>
    </ul>
</div>
<fieldset>
    <div class="clearfix">
        <label for="title">标题：</label>
        <div class="input">
            <input type="text" size="30" name="title" id="title" class="xlarge">
            ，你们有什么想问的？
        </div>
    </div>
    <div class="clearfix">
        <label for="content">内容：</label>
        <div class="input">
            <textarea rows="3" name="content" id="content" class="xxlarge"></textarea>
        </div>
    </div>
    <div class="actions">
        <input type="submit" value="发表" class="btn primary">&nbsp;
        <button class="btn" type="reset">取消</button>
    </div>
</fieldset>
