<fieldset>
    <div class="clearfix">
        <label for="title">标题：</label>
        <div class="input">
            <input type="text" size="30" name="title" id="title" class="xlarge">
            ，你们有什么想问的？
        </div>
    </div>
    <div class="clearfix">
        <label for="content">内容：</label>
        <div class="input">
            <textarea rows="3" name="content" id="content" class="xxlarge"></textarea>
        </div>
    </div>
    <div class="actions">
        <?=$this->element->getElement('csrf')?>
        <input type="submit" value="发表" class="btn primary">&nbsp;
        <button class="btn" type="reset">取消</button>
    </div>
</fieldset>
