<div class="span11">
    <div id="view-content">
        <div id="topic-example">
            <h3>例子：</h3>
            <ul>
                <li>我是门口摊大饼的，你们有什么想问的？</li>
                <li>我是一个在非洲厮混过几年的颓废男纸，你们有什么想问的？</li>
                <li>我的男朋友是外国人，你们有什么想问的？</li>
                <li>我是单身女青年，有什么想问的？</li>
            </ul>
        </div>
        <?=$this->form;?>
    </div>
</div>
<div class="span5">
    <h3>小提示：</h3>
    <ul>
        <li>
            想一个你<strong>独特的身份或经历</strong>。
        </li>
        <li>
            选一个能<strong>引起别人提问兴趣</strong>的题目。
        </li>
        <li>
            准备回到你能回答的任何问题吧！
        </li>
    </ul>
</div>
