<div class="span11">
    <div id="topic-view">
        <h2><?php echo $this->escape($this->topic->getTitle()); ?></h2>
        <p>
            <?php echo $this->escape($this->topic->getContent()); ?>
        </p>
        <div id="topic-view-questions" class="row">
        <?php foreach($this->answeredQuestions as $question):?>
            <div class="vote-column span1">
                <a class="vote up">Up</a>
                <div class="vote-count">123</div>
                <a class="vote down">Down</a>
            </div>
            <div class="span9 question">
                <h4 style="display: inline;"><?php echo $this->escape($question->getContent());?></h4>
                <p>
                    <?php echo $question->getAnswer()->getContent();?>
                </p>
            </div>
        <?php endforeach;?>
        </div>
    </div>
</div>
<div class="span5">
    <?php if(!$this->topic->isBelongTo(
            Zend_Registry::isRegistered('authUser') ? Zend_Registry::get('authUser') : null)
        ):?>
    <a class="btn large primary" href="<?php echo $this->url(array(
        'controller' => 'topic',
        'action'     => 'new'
    ))?>">
        订阅该话题
    </a>
    <?php endif;?>
    <div id="topic-left" class="row show-grid">
        <div id="topic-left-user" class="span5">
            <?php echo $this->escape($this->topic->getUser()->getNickname())?>
        </div>
        <div id="topic-left-add-questions" class="span5">
            <p>
                向<?php echo $this->escape($this->topic->getUser()->getNickname())?>提问题:
            </p>
            <?php echo $this->questionForm;?>
        </div>
        <div id="topic-left-questions" class="span5">
            <p>
                <?php echo $this->escape($this->topic->getUser()->getNickname())?>未回答的问题
            </p>
            <?php foreach($this->unansweredQuestions as $question):?>
            <div class="row">
                <div class="vote-column span1">
                    <a class="vote up">Up</a>
                    <div class="vote-count">123</div>
                    <a class="vote down">Down</a>
                </div>
                <div class="topic-unaswered-questions span4">
                    <div>
                        <?php echo $this->escape($question->getContent()); ?>
                    </div>
                    <?php if($this->topic->isBelongTo(
                        Zend_Registry::isRegistered('authUser') ? Zend_Registry::get('authUser') : null)
                    ):?>
                    <div>
                        <a href="<?php echo $this->url(array(
                            'questionId' => $question->getId(),
                        ), 'answerNew', true);?>"><button id="answer-button" class="btn success">回答</button></a>
                        
                        <button id="remove-button" class="btn danger">忽略</button>
                    </div>
                    <?php endif;?>
                </div>
            </div>
            <?php endforeach;?>
        </div>
    </div>
</div>