<?= $this->doctype(); ?>

<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <?= $this->headTitle(); ?>

        <?= $this->headMeta(); ?>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?= $this->headLink(); ?>

        <?= $this->headStyle(); ?>

        <?= $this->headScript(); ?>

    </head>
    <body>
        <div id="top-nav" class="topbar">
            <div class="fill">
                <div class="container">
                    <a class="brand" href="#">Project name</a>
                    <ul class="nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                    <form action="" class="pull-right">
                        <input class="input-small" type="text" placeholder="Username">
                        <input class="input-small" type="password" placeholder="Password">
                        <button class="btn" type="submit">Sign in</button>
                    </form>
                </div>
            </div>
        </div>

        <div id="page-container" class="container">
            <div class="content">
                <div class="page-header">
                    <h1>Page name <small>Supporting text or tagline</small></h1>
                </div>
                <div class="row">
                    <div class="span10">
                        <?php echo $this->layout()->content; ?>
                    </div>
                    <div class="span4">
                        <h3>Secondary content</h3>
                    </div>
                </div>
            </div>

            <footer>
                <p>&copy; Company 2011</p>
            </footer>

        </div> <!-- /container -->

    </body>
</html>