<?= $this->doctype(); ?>

<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <?= $this->headTitle(); ?>

        <?= $this->headMeta(); ?>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?= $this->headLink(); ?>

        <?= $this->headStyle(); ?>

        <?= $this->headScript(); ?>

    </head>
    <body>
        <div id="top-nav" class="topbar">
            <div class="fill">
                <div class="container">
                    <a href="<?php echo $this->baseUrl('/'); ?>" class="brand">I'm OOXX</a>
                    <ul class="nav">
                        <li><a href="#">搜索</a></li>
                    </ul>
                    <ul class="nav secondary-nav">
                        <?php if (Zend_Registry::isRegistered('authUser')): ?>
                        <li>
                            <a href="#">首页</a>
                        </li>
                        <li>
                            <a href=""><?php echo Zend_Registry::get('authUser')->getNickname(); ?></a>
                        </li>
                        <li>
                        <a href="<?php echo $this->baseUrl('/user/settings')?>">设置</a>
                        </li>
                        <li>
                            <a href="<?php
                            echo $this->url(array(
                                'controller' => 'user',
                                'action' => 'logout',
                            ))
                            ?>">退出</a>
                        </li>
                        <?php else: ?>
                        <li>
                            <a href="<?php
                                echo $this->url(array(
                                    'controller' => 'user',
                                    'action'     => 'login'
                                ));
                            ?>">登录</a>
                        </li>
                        <li>
                            <a href="<?php
                                echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'register',
                                ));
                            ?>">注册</a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>

        <div id="page-container" class="container">
            <div class="content">
                <div class="page-header">
                    <h1>我是OOXX <small>你们有什么想问的？</small></h1>
                </div>
                <div class="row">
<?php echo $this->layout()->content; ?>
                </div>
            </div>

            <footer>
                <p>&copy; Company 2011</p>
            </footer>

        </div> <!-- /container -->

    </body>
</html>
