<?= $this->doctype(); ?>

<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <?= $this->headTitle(); ?>

        <?= $this->headMeta(); ?>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?= $this->headLink(); ?>

        <?= $this->headStyle(); ?>

        <?= $this->headScript(); ?>

    </head>
    <body>
        <div id="top-nav" class="topbar">
            <div class="fill">
                <div class="container">
                    <a href="<?php echo $this->baseUrl('/'); ?>" class="brand">I'm OOXX</a>
                    <ul class="nav">
                        <li><a href="#">搜索</a></li>
                    </ul>
                    <?php if (Zend_Registry::isRegistered('authUser')): ?>
                        <ul class="nav secondary-nav">
                            <li>
                                <a href="#">首页</a>
                            </li>
                            <li>
                                <a href=""><?php echo Zend_Registry::get('authUser')->getNickname(); ?></a>
                            </li>
                            <li>
                            <a href="<?php echo $this->baseUrl('/user/settings')?>">设置</a>
                            </li>
                            <li>
                                <a href="<?php
                                echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'logout',
                                ))
                                ?>">退出</a>
                            </li>
                        </ul>
                        <?php else: ?>
                        <form id="user-top-login-form" enctype="application/x-www-form-urlencoded" action="/user/login" method="post" class="pull-right">
                            <div class="dl_handle_2" id="dl_handle">
                                <ul data-keyboard="true" data-backdrop="true" data-controls-modal="denglu-model">
                                    <li>
                                        <img src="http://open.denglu.cc//images/denglu_second_icon_3.gif" alt="新浪微博">
                                    </li>
                                    <li>
                                        <img src="http://open.denglu.cc//images/denglu_second_icon_7.gif" alt="人人网">
                                    </li>
                                    <li>
                                        <img src="http://open.denglu.cc//images/denglu_second_icon_13.gif" alt="QQ空间">
                                    </li>
                                    <li>
                                        <img src="http://open.denglu.cc//images/denglu_second_icon_9.gif" alt="豆瓣网">
                                    </li>
                                </ul>
                            </div>
                            <div id="denglu-model" class="modal hide fade">
                                <div class="modal-header">
                                    <a href="#" class="close">&times;</a>
                                    <h3>合作网站帐号登录</h3>
                                </div>
                                <div class="modal-body">
                                    <div class="denglu_con" id="mediashow1">
                                        <ul>
                                            <li>
                                                <a href="http://open.denglu.cc/transfer/sina?appid=9758" title="用新浪微博登录" class="denglu_ico denglu_sina">用新浪微博登录</a>
                                            </li>
                                            <li>
                                                <a href="jhttp://open.denglu.cc/transfer/renren?appid=9758" title="用人人网登录" class="denglu_ico denglu_renren">用人人网登录</a>
                                            </li>
                                            <li>
                                                <a href="http://open.denglu.cc/transfer/qzone?appid=9758" title="用QQ空间登录" class="denglu_ico denglu_qzone">用QQ空间登录</a>
                                            </li>
                                            <li>
                                                <a href="http://open.denglu.cc/transfer/douban?appid=9758" title="用豆瓣网登录" class="denglu_ico denglu_douban">用豆瓣网登录</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <input class="input-small" type="text" name="email" placeholder="邮箱">
                            <input class="input-small" type="password" name="password" placeholder="密码">
                            <button class="btn" type="submit">登录</button>
                            <span><a href="<?php
                                echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'register',
                                ));
                                ?>">注册</a></span>
                        </form>
                        <?php endif; ?>
                </div>
            </div>
        </div>

        <div id="page-container" class="container">
            <div class="content">
                <div class="page-header">
                    <h1>我是OOXX <small>你们有什么想问的？</small></h1>
                </div>
                <div class="row">
<?php echo $this->layout()->content; ?>
                </div>
            </div>

            <footer>
                <p>&copy; Company 2011</p>
            </footer>

        </div> <!-- /container -->

    </body>
</html>
