<?= $this->doctype(); ?>

<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <?= $this->headTitle(); ?>

        <?= $this->headMeta(); ?>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?= $this->headLink(); ?>

        <?= $this->headStyle(); ?>

        <?= $this->headScript(); ?>

    </head>
    <body>
        <div id="top-nav" class="topbar">
            <div class="fill">
                <div class="container">
                    <ul class="nav">
                        <li class="active"><a href="<?php echo $this->baseUrl('/')?>">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                    <?php echo $this->layout()->topLogin; ?>
                </div>
            </div>
        </div>

        <div id="page-container" class="container">
            <div class="content">
                <div class="page-header">
                    <h1>我是OOXX <small>你们有什么想问的？</small></h1>
                </div>
                <div class="row">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>

            <footer>
                <p>&copy; Company 2011</p>
            </footer>

        </div> <!-- /container -->

    </body>
</html>