<fieldset>
    <div class="clearfix">
        <label for="title">邮箱：</label>
        <div class="input">
            <input type="text" size="30" name="email" id="email" class="xlarge" />
        </div>
    </div>
    <div class="clearfix">
        <label for="content">密码：</label>
        <div class="input">
            <input type="password" size="30" name="password" id="password" class="xlarge" />
        </div>
    </div>
    <div class="clearfix">
        <label for="content">重复密码：</label>
        <div class="input">
            <input type="password" size="30" name="re-password" id="re-password" class="xlarge" />
        </div>
    </div>
    <div class="clearfix">
        <label for="content">名号：</label>
        <div class="input">
            <input type="nickname" size="30" name="nickname" id="nickname" class="xlarge" />
        </div>
    </div>
    <div class="actions">
        <input type="submit" value="注册" class="btn primary">&nbsp;
        <button class="btn" type="reset">重填</button>
    </div>
</fieldset>