<fieldset>
    <legend>帐号信息</legend>
    <div class="clearfix">
        <label for="disabledInput">登录邮箱</label>
        <div class="input">
            <input type="text" size="30" name="xlInput" id="xlInput" class="xlarge">
        </div>
    </div> 
    <div class="clearfix">
        <label for="disabledInput">登录密码</label>
        <div class="input">
            <input type="password" size="30" name="xlInput" id="xlInput" class="xlarge">
        </div>
    </div> 
    <div class="clearfix">
        <label for="disabledInput">确认密码</label>
        <div class="input">
            <input type="password" size="30" name="xlInput" id="xlInput" class="xlarge">
        </div>
    </div> 
    <div class="clearfix">
        <label for="textarea">个人介绍</label>
        <div class="input">
            <textarea rows="3" name="textarea2" id="textarea2" class="xxlarge"></textarea>
        </div>
    </div>
    <div class="actions">
        <input type="submit" value="保存设置" class="btn primary">
    </div>
</fieldset>

