<div class="dl_handle_2" id="dl_handle">
    <ul data-keyboard="true" data-backdrop="true" data-controls-modal="denglu-model">
        <li>
            <img src="http://open.denglu.cc//images/denglu_second_icon_3.gif" alt="新浪微博">
        </li>
        <li>
            <img src="http://open.denglu.cc//images/denglu_second_icon_7.gif" alt="人人网">
        </li>
        <li>
            <img src="http://open.denglu.cc//images/denglu_second_icon_13.gif" alt="QQ空间">
        </li>
        <li>
            <img src="http://open.denglu.cc//images/denglu_second_icon_9.gif" alt="豆瓣网">
        </li>
    </ul>
</div>
<div id="denglu-model" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close">&times;</a>
        <h3>合作网站帐号登录</h3>
    </div>
    <div class="modal-body">
        <div class="denglu_con" id="mediashow1">
            <ul>
                <li>
                    <a href="http://open.denglu.cc/transfer/sina?appid=9758" title="用新浪微博登录" class="denglu_ico denglu_sina">用新浪微博登录</a>
                </li>
                <li>
                    <a href="jhttp://open.denglu.cc/transfer/renren?appid=9758" title="用人人网登录" class="denglu_ico denglu_renren">用人人网登录</a>
                </li>
                <li>
                    <a href="http://open.denglu.cc/transfer/qzone?appid=9758" title="用QQ空间登录" class="denglu_ico denglu_qzone">用QQ空间登录</a>
                </li>
                <li>
                    <a href="http://open.denglu.cc/transfer/douban?appid=9758" title="用豆瓣网登录" class="denglu_ico denglu_douban">用豆瓣网登录</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<input class="input-small" type="text" name="email" placeholder="邮箱">
<input class="input-small" type="password" name="password" placeholder="密码">
<button class="btn" type="submit">登录</button>
<span><a href="<?php echo $this->url(array(
    'controller' => 'user',
    'action'     => 'register',
));?>">注册</a></span>
