<?php if(Zend_Registry::isRegistered('authUser')):?>
    <ul class="nav secondary-nav">
            <li>
                <a href="#">首页</a>
            </li>
            <li>
                <a href=""><?php echo Zend_Registry::get('authUser')->getNickname(); ?></a>
            </li>
            <li>
                <a href="#">设置</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array(
                    'controller' => 'user',
                    'action'     => 'logout',
                ))?>">退出</a>
            </li>
    </ul>
<?php else:?>
    <?php echo $this->form;?>
<?php endif;?>